# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define() do

  create_table "action_type", :id => false, :force => true do |t|
    t.column "ActionType_ID", :integer,                 :null => false
    t.column "ActionName",    :string,  :default => "", :null => false
  end

  add_index "action_type", ["actiontype_id"], :name => "primary", :unique => true

  create_table "answer", :id => false, :force => true do |t|
    t.column "Answer_ID", :integer, :limit => 19,                     :null => false
    t.column "hasLAcode", :boolean, :limit => nil, :default => false
    t.column "LAcode",    :string
  end

  add_index "answer", ["answer_id"], :name => "primary", :unique => true

  create_table "answer_list", :id => false, :force => true do |t|
    t.column "AnswerList_ID", :integer, :limit => 19, :null => false
    t.column "Description",   :text
  end

  add_index "answer_list", ["answerlist_id"], :name => "primary", :unique => true

  create_table "answer_list_content", :id => false, :force => true do |t|
    t.column "AnswerListContent_ID", :integer, :limit => 19,                 :null => false
    t.column "Value",                :string,                :default => "", :null => false
    t.column "AnswerOrder",          :integer,                               :null => false
    t.column "AnswerList_ID",        :integer, :limit => 19
    t.column "Answer_ID",            :integer, :limit => 19
  end

  add_index "answer_list_content", ["answerlistcontent_id"], :name => "primary", :unique => true
  add_index "answer_list_content", ["answerlist_id"], :name => "fk_answer_list_content_answerlist_id"
  add_index "answer_list_content", ["answer_id"], :name => "fk_answer_list_content_answer_id"

  create_table "answer_list_denormalized", :id => false, :force => true do |t|
    t.column "AnswerListDenormalized_ID",    :integer, :limit => 19,                 :null => false
    t.column "AnswerListDenormalizedString", :text,                  :default => "", :null => false
    t.column "LanguageCode",                 :string,  :limit => 2,  :default => "", :null => false
    t.column "AnswerList_ID",                :integer, :limit => 19
  end

  add_index "answer_list_denormalized", ["answerlistdenormalized_id"], :name => "primary", :unique => true
  add_index "answer_list_denormalized", ["answerlist_id"], :name => "fk_answer_list_denormalized_answerlist_id"

  create_table "answer_localized", :id => false, :force => true do |t|
    t.column "AnswerLocalized_ID", :integer, :limit => 19,                 :null => false
    t.column "LanguageCode",       :string,  :limit => 2,  :default => "", :null => false
    t.column "AnswerString",       :text
    t.column "Answer_ID",          :integer, :limit => 19
  end

  add_index "answer_localized", ["answerlocalized_id"], :name => "primary", :unique => true
  add_index "answer_localized", ["answer_id"], :name => "fk_answer_localized_answer_id"

  create_table "code_system", :id => false, :force => true do |t|
    t.column "CodeSystem_ID",  :integer, :null => false
    t.column "CodeSystemName", :string
    t.column "CodeSystemOID",  :string
  end

  add_index "code_system", ["codesystem_id"], :name => "primary", :unique => true

  create_table "data_element", :id => false, :force => true do |t|
    t.column "DataElement_ID",       :integer,  :limit => 19, :null => false
    t.column "Comments",             :text
    t.column "Time_Stamp",           :datetime
    t.column "LanguageCode",         :string,   :limit => 2
    t.column "DisplayNum",           :integer,                :null => false
    t.column "AnswerString",         :text
    t.column "itemVacillation",      :integer
    t.column "NullFlavor_ID",        :integer,                :null => false
    t.column "responseLatency",      :integer
    t.column "QuestionAsAsked",      :text
    t.column "responseDuration",     :integer
    t.column "DataElementSequence",  :integer,                :null => false
    t.column "Answer_ID",            :integer,  :limit => 19
    t.column "InstrumentContent_ID", :integer,  :limit => 19
    t.column "InstrumentSession_ID", :integer,  :limit => 19
  end

  add_index "data_element", ["dataelement_id"], :name => "primary", :unique => true
  add_index "data_element", ["instrumentcontent_id"], :name => "fk_data_element_instrumentcontent_id"
  add_index "data_element", ["instrumentsession_id"], :name => "fk_data_element_instrumentsession_id"

  create_table "data_type", :id => false, :force => true do |t|
    t.column "DataType_ID", :integer,                 :null => false
    t.column "DataType",    :string,  :default => "", :null => false
  end

  add_index "data_type", ["datatype_id"], :name => "primary", :unique => true

  create_table "dialogix_user", :id => false, :force => true do |t|
    t.column "DialogixUser_ID", :integer,                 :null => false
    t.column "first_name",      :string,  :default => "", :null => false
    t.column "last_name",       :string,  :default => "", :null => false
    t.column "user_name",       :string,  :default => "", :null => false
    t.column "email",           :string,  :default => "", :null => false
    t.column "phone",           :string,  :default => "", :null => false
    t.column "pwd",             :string,  :default => "", :null => false
  end

  add_index "dialogix_user", ["dialogixuser_id"], :name => "primary", :unique => true

  create_table "display_type", :id => false, :force => true do |t|
    t.column "DisplayType_ID", :integer,                                   :null => false
    t.column "SASinformat",    :string,                 :default => "",    :null => false
    t.column "SASformat",      :string,                 :default => "",    :null => false
    t.column "DisplayType",    :string,                 :default => "",    :null => false
    t.column "SPSSlevel",      :string,                 :default => "",    :null => false
    t.column "SPSSformat",     :string,                 :default => "",    :null => false
    t.column "LOINCscale",     :string,                 :default => "",    :null => false
    t.column "HasAnswerList",  :boolean, :limit => nil, :default => false
    t.column "DataType_ID",    :integer
  end

  add_index "display_type", ["displaytype_id"], :name => "primary", :unique => true
  add_index "display_type", ["datatype_id"], :name => "fk_display_type_datatype_id"

  create_table "function_name", :id => false, :force => true do |t|
    t.column "FunctionName_ID", :integer,                 :null => false
    t.column "Syntax",          :text,    :default => "", :null => false
    t.column "Description",     :text,    :default => "", :null => false
    t.column "Name",            :string,  :default => "", :null => false
    t.column "Definition",      :text,    :default => "", :null => false
  end

  add_index "function_name", ["functionname_id"], :name => "primary", :unique => true

  create_table "help", :id => false, :force => true do |t|
    t.column "Help_ID", :integer, :limit => 19, :null => false
  end

  add_index "help", ["help_id"], :name => "primary", :unique => true

  create_table "help_localized", :id => false, :force => true do |t|
    t.column "HelpLocalized_ID", :integer, :limit => 19,                 :null => false
    t.column "LanguageCode",     :string,  :limit => 2,  :default => "", :null => false
    t.column "HelpString",       :text
    t.column "Help_ID",          :integer, :limit => 19
  end

  add_index "help_localized", ["helplocalized_id"], :name => "primary", :unique => true
  add_index "help_localized", ["help_id"], :name => "fk_help_localized_help_id"

  create_table "inst_ver_1", :id => false, :force => true do |t|
    t.column "InstrumentSession_ID",    :integer,                                   :null => false
    t.column "StartTime",               :timestamp,                                 :null => false
    t.column "LastAccessTime",          :timestamp,                                 :null => false
    t.column "DisplayNum",              :integer,                                   :null => false
    t.column "LanguageCode",            :string,    :limit => 2,  :default => "en", :null => false
    t.column "InstrumentStartingGroup", :integer,                                   :null => false
    t.column "CurrentGroup",            :integer,                                   :null => false
    t.column "LastAction",              :string,    :limit => 35
    t.column "statusMsg",               :string,    :limit => 35, :default => "",   :null => false
    t.column "instructions",            :text
    t.column "q1",                      :text
    t.column "q2",                      :text
    t.column "q3",                      :text
    t.column "q3a",                     :text
    t.column "q3b",                     :text
    t.column "q3c",                     :text
    t.column "q3d",                     :text
    t.column "q3e",                     :text
    t.column "q3f",                     :text
    t.column "q3g",                     :text
    t.column "q3h",                     :text
    t.column "q3i",                     :text
    t.column "q3j",                     :text
    t.column "q4",                      :text
    t.column "q4a",                     :text
    t.column "q4b",                     :text
    t.column "q4c",                     :text
    t.column "q4d",                     :text
    t.column "q5",                      :text
    t.column "q5a",                     :text
    t.column "q5b",                     :text
    t.column "q5c",                     :text
    t.column "q6",                      :text
    t.column "q7",                      :text
    t.column "q8",                      :text
    t.column "q9",                      :text
    t.column "q9a",                     :text
    t.column "q9b",                     :text
    t.column "q9c",                     :text
    t.column "q9d",                     :text
    t.column "q9e",                     :text
    t.column "q9f",                     :text
    t.column "q9g",                     :text
    t.column "q9h",                     :text
    t.column "q9i",                     :text
    t.column "q10",                     :text
    t.column "q11",                     :text
    t.column "q11a",                    :text
    t.column "q11b",                    :text
    t.column "q11c",                    :text
    t.column "q11d",                    :text
    t.column "PF_total",                :text
    t.column "PF_score",                :text
    t.column "RP_total",                :text
    t.column "RP_score",                :text
    t.column "RE_total",                :text
    t.column "RE_score",                :text
    t.column "EV_total",                :text
    t.column "EV_score",                :text
    t.column "MH_total",                :text
    t.column "MH_score",                :text
    t.column "SF_total",                :text
    t.column "SF_score",                :text
    t.column "P_total",                 :text
    t.column "P_score",                 :text
    t.column "GH_total",                :text
    t.column "GH_score",                :text
    t.column "HC_total",                :text
    t.column "HC_score",                :text
    t.column "report",                  :text
  end

  add_index "inst_ver_1", ["instrumentsession_id"], :name => "primary", :unique => true
  add_index "inst_ver_1", ["languagecode"], :name => "k1_instver_1"

  create_table "inst_ver_2", :id => false, :force => true do |t|
    t.column "InstrumentSession_ID",    :integer,                                   :null => false
    t.column "StartTime",               :timestamp,                                 :null => false
    t.column "LastAccessTime",          :timestamp,                                 :null => false
    t.column "DisplayNum",              :integer,                                   :null => false
    t.column "LanguageCode",            :string,    :limit => 2,  :default => "en", :null => false
    t.column "InstrumentStartingGroup", :integer,                                   :null => false
    t.column "CurrentGroup",            :integer,                                   :null => false
    t.column "LastAction",              :string,    :limit => 35
    t.column "statusMsg",               :string,    :limit => 35, :default => "",   :null => false
    t.column "Disclaimer",              :text
    t.column "Title",                   :text
    t.column "Intro",                   :text
    t.column "date",                    :text
    t.column "age",                     :text
    t.column "female",                  :text
    t.column "q1intro",                 :text
    t.column "q1a",                     :text
    t.column "q1b",                     :text
    t.column "q1c",                     :text
    t.column "q1d",                     :text
    t.column "q1e",                     :text
    t.column "q1f",                     :text
    t.column "q1g",                     :text
    t.column "q1h",                     :text
    t.column "q1i",                     :text
    t.column "q1j",                     :text
    t.column "q1k",                     :text
    t.column "q1l",                     :text
    t.column "q1m",                     :text
    t.column "q2intro",                 :text
    t.column "q2a",                     :text
    t.column "q2b",                     :text
    t.column "q2c",                     :text
    t.column "q2d",                     :text
    t.column "q2e",                     :text
    t.column "q2f",                     :text
    t.column "q2g",                     :text
    t.column "q2h",                     :text
    t.column "q2i",                     :text
    t.column "q3intro",                 :text
    t.column "q3a",                     :text
    t.column "q3intro2",                :text
    t.column "q3b",                     :text
    t.column "q3c",                     :text
    t.column "q3d",                     :text
    t.column "q4intro",                 :text
    t.column "q4a",                     :text
    t.column "q4b",                     :text
    t.column "q4c",                     :text
    t.column "q4d",                     :text
    t.column "q4e",                     :text
    t.column "q4f",                     :text
    t.column "q4g",                     :text
    t.column "q4h",                     :text
    t.column "q4i",                     :text
    t.column "q4j",                     :text
    t.column "q4k",                     :text
    t.column "q5intro",                 :text
    t.column "q5a",                     :text
    t.column "q5intro1",                :text
    t.column "q5b",                     :text
    t.column "q5c",                     :text
    t.column "q5d",                     :text
    t.column "q5e",                     :text
    t.column "q5f",                     :text
    t.column "q5g",                     :text
    t.column "q6intro",                 :text
    t.column "q6a",                     :text
    t.column "q6b",                     :text
    t.column "q6intro1",                :text
    t.column "q6c",                     :text
    t.column "q7intro",                 :text
    t.column "q7a",                     :text
    t.column "q7b",                     :text
    t.column "q7c",                     :text
    t.column "q7d",                     :text
    t.column "q8",                      :text
    t.column "q9",                      :text
    t.column "q10intro",                :text
    t.column "q10a",                    :text
    t.column "q10b",                    :text
    t.column "q10c",                    :text
    t.column "q10d",                    :text
    t.column "q10e",                    :text
    t.column "sxSom",                   :text
    t.column "dxSom",                   :text
    t.column "sxD",                     :text
    t.column "dxMDS",                   :text
    t.column "dxODS",                   :text
    t.column "sxPanic",                 :text
    t.column "sxAttack",                :text
    t.column "dxPanic",                 :text
    t.column "sxAnxiety",               :text
    t.column "dxAnxiety",               :text
    t.column "sxBul",                   :text
    t.column "sxPurge",                 :text
    t.column "dxBulNer",                :text
    t.column "dxBulEatDis",             :text
    t.column "sxAlcAbu",                :text
    t.column "dxAlcAbu",                :text
    t.column "Report",                  :text
    t.column "Report1",                 :text
    t.column "Report2",                 :text
    t.column "Report3",                 :text
    t.column "Report4",                 :text
    t.column "Report5",                 :text
    t.column "Report6",                 :text
    t.column "anySx",                   :text
    t.column "q11",                     :text
    t.column "q12intro",                :text
    t.column "q12a",                    :text
    t.column "q12b",                    :text
    t.column "q12c",                    :text
    t.column "q12d",                    :text
    t.column "q12e",                    :text
    t.column "q12f",                    :text
    t.column "q12g",                    :text
    t.column "q12h",                    :text
    t.column "q12i",                    :text
    t.column "q12j",                    :text
    t.column "q13",                     :text
    t.column "q14",                     :text
    t.column "q15",                     :text
    t.column "q16intro",                :text
    t.column "q16a",                    :text
    t.column "q16b",                    :text
    t.column "q16intro1",               :text
    t.column "q16c",                    :text
    t.column "q16intro2",               :text
    t.column "q16d",                    :text
    t.column "q16e",                    :text
    t.column "q16f",                    :text
    t.column "Notes",                   :text
  end

  add_index "inst_ver_2", ["instrumentsession_id"], :name => "primary", :unique => true
  add_index "inst_ver_2", ["languagecode"], :name => "k1_instver_2"

  create_table "instrument", :id => false, :force => true do |t|
    t.column "Instrument_ID",         :integer, :limit => 19,                 :null => false
    t.column "InstrumentDescription", :text
    t.column "InstrumentName",        :string,                :default => "", :null => false
  end

  add_index "instrument", ["instrument_id"], :name => "primary", :unique => true

  create_table "instrument_content", :id => false, :force => true do |t|
    t.column "InstrumentContent_ID", :integer, :limit => 19,                 :null => false
    t.column "DefaultAnswer",        :text
    t.column "SPSSformat",           :string
    t.column "Concept",              :text
    t.column "SASinformat",          :string
    t.column "isReadOnly",           :integer,                               :null => false
    t.column "SASformat",            :string
    t.column "GroupNum",             :integer,                               :null => false
    t.column "ItemSequence",         :integer,                               :null => false
    t.column "ItemActionType",       :string
    t.column "isRequired",           :integer,                               :null => false
    t.column "isMessage",            :integer,                               :null => false
    t.column "DisplayName",          :text
    t.column "FormatMask",           :text
    t.column "Relevance",            :text,                  :default => "", :null => false
    t.column "VarName_ID",           :integer, :limit => 19
    t.column "Help_ID",              :integer, :limit => 19
    t.column "DisplayType_ID",       :integer
    t.column "Item_ID",              :integer, :limit => 19
    t.column "InstrumentVersion_ID", :integer, :limit => 19
    t.column "Readback_ID",          :integer, :limit => 19
  end

  add_index "instrument_content", ["instrumentcontent_id"], :name => "primary", :unique => true
  add_index "instrument_content", ["readback_id"], :name => "fk_instrument_content_readback_id"
  add_index "instrument_content", ["displaytype_id"], :name => "fk_instrument_content_displaytype_id"
  add_index "instrument_content", ["item_id"], :name => "fk_instrument_content_item_id"
  add_index "instrument_content", ["instrumentversion_id"], :name => "fk_instrument_content_instrumentversion_id"
  add_index "instrument_content", ["varname_id"], :name => "fk_instrument_content_varname_id"
  add_index "instrument_content", ["help_id"], :name => "fk_instrument_content_help_id"

  create_table "instrument_hash", :id => false, :force => true do |t|
    t.column "InstrumentHash_ID", :integer, :limit => 19,                 :null => false
    t.column "NumInstructions",   :integer,                               :null => false
    t.column "NumEquations",      :integer,                               :null => false
    t.column "NumVars",           :integer,                               :null => false
    t.column "NumQuestions",      :integer,                               :null => false
    t.column "InstrumentMD5",     :string,                :default => "", :null => false
    t.column "NumBranches",       :integer,                               :null => false
    t.column "NumTailorings",     :integer,                               :null => false
    t.column "NumLanguages",      :integer,                               :null => false
    t.column "VarListMD5",        :string,                :default => "", :null => false
    t.column "LanguageList_ID",   :integer
  end

  add_index "instrument_hash", ["instrumenthash_id"], :name => "primary", :unique => true
  add_index "instrument_hash", ["languagelist_id"], :name => "fk_instrument_hash_languagelist_id"

  create_table "instrument_header", :id => false, :force => true do |t|
    t.column "InstrumentHeader_ID",  :integer, :limit => 19,                 :null => false
    t.column "Value",                :text,                  :default => "", :null => false
    t.column "ReservedWord_ID",      :integer
    t.column "InstrumentVersion_ID", :integer, :limit => 19
  end

  add_index "instrument_header", ["instrumentheader_id"], :name => "primary", :unique => true
  add_index "instrument_header", ["reservedword_id"], :name => "fk_instrument_header_reservedword_id"
  add_index "instrument_header", ["instrumentversion_id"], :name => "fk_instrument_header_instrumentversion_id"

  create_table "instrument_load_error", :id => false, :force => true do |t|
    t.column "InstrumentLoadError_ID", :integer, :limit => 19, :null => false
    t.column "sourceRow",              :integer
    t.column "sourceColumn",           :integer
    t.column "ErrorMessage",           :text
    t.column "logLevel",               :integer
    t.column "InstrumentVersion_ID",   :integer, :limit => 19
  end

  add_index "instrument_load_error", ["instrumentloaderror_id"], :name => "primary", :unique => true
  add_index "instrument_load_error", ["instrumentversion_id"], :name => "fk_instrument_load_error_instrumentversion_id"

  create_table "instrument_session", :id => false, :force => true do |t|
    t.column "InstrumentSession_ID",      :integer,  :limit => 19,                 :null => false
    t.column "StatusMsg",                 :string
    t.column "InstrumentSessionFileName", :text
    t.column "StartTime",                 :datetime,                               :null => false
    t.column "DisplayNum",                :integer,                                :null => false
    t.column "LanguageCode",              :string,                 :default => "", :null => false
    t.column "CurrentGroup",              :integer,                                :null => false
    t.column "InstrumentStartingGroup",   :integer,                                :null => false
    t.column "LastAccessTime",            :datetime,                               :null => false
    t.column "Instrument_ID",             :integer,  :limit => 19
    t.column "InstrumentVersion_ID",      :integer,  :limit => 19
    t.column "ActionType_ID",             :integer
    t.column "DialogixUser_ID",           :integer
  end

  add_index "instrument_session", ["instrumentsession_id"], :name => "primary", :unique => true
  add_index "instrument_session", ["instrument_id"], :name => "fk_instrument_session_instrument_id"
  add_index "instrument_session", ["instrumentversion_id"], :name => "fk_instrument_session_instrumentversion_id"
  add_index "instrument_session", ["actiontype_id"], :name => "fk_instrument_session_actiontype_id"
  add_index "instrument_session", ["dialogixuser_id"], :name => "fk_instrument_session_dialogixuser_id"

  create_table "instrument_version", :id => false, :force => true do |t|
    t.column "InstrumentVersion_ID",      :integer,  :limit => 19,                     :null => false
    t.column "LOINC_NUM",                 :string
    t.column "CreationTimeStamp",         :datetime,                                   :null => false
    t.column "VersionString",             :string,                  :default => "",    :null => false
    t.column "InstrumentVersionFileName", :text
    t.column "InstrumentStatus",          :integer
    t.column "hasLOINCcode",              :boolean,  :limit => nil, :default => false
    t.column "InstrumentNotes",           :text
    t.column "InstrumentHash_ID",         :integer,  :limit => 19
    t.column "Instrument_ID",             :integer,  :limit => 19
  end

  add_index "instrument_version", ["instrumentversion_id"], :name => "primary", :unique => true
  add_index "instrument_version", ["instrument_id"], :name => "fk_instrument_version_instrument_id"
  add_index "instrument_version", ["instrumenthash_id"], :name => "fk_instrument_version_instrumenthash_id"

  create_table "item", :id => false, :force => true do |t|
    t.column "Item_ID",       :integer, :limit => 19,                     :null => false
    t.column "ItemType",      :string,                 :default => "",    :null => false
    t.column "hasLOINCcode",  :boolean, :limit => nil, :default => false
    t.column "LOINC_NUM",     :string
    t.column "AnswerList_ID", :integer, :limit => 19
    t.column "Validation_ID", :integer, :limit => 19
    t.column "Question_ID",   :integer, :limit => 19
    t.column "DataType_ID",   :integer
  end

  add_index "item", ["item_id"], :name => "primary", :unique => true
  add_index "item", ["validation_id"], :name => "fk_item_validation_id"
  add_index "item", ["question_id"], :name => "fk_item_question_id"
  add_index "item", ["datatype_id"], :name => "fk_item_datatype_id"
  add_index "item", ["answerlist_id"], :name => "fk_item_answerlist_id"

  create_table "item_usage", :id => false, :force => true do |t|
    t.column "ItemUsage_ID",         :integer,  :limit => 19,                 :null => false
    t.column "Answer_ID",            :integer,  :limit => 19
    t.column "NullFlavor_ID",        :integer,                                :null => false
    t.column "ItemUsageSequence",    :integer,                                :null => false
    t.column "QuestionAsAsked",      :text,                   :default => "", :null => false
    t.column "DisplayNum",           :integer,                                :null => false
    t.column "itemVacillation",      :integer
    t.column "WhenAsMS",             :integer,  :limit => 19,                 :null => false
    t.column "responseLatency",      :integer
    t.column "AnswerString",         :text
    t.column "responseDuration",     :integer
    t.column "GroupNum",             :integer,                                :null => false
    t.column "Comments",             :text,                   :default => "", :null => false
    t.column "Time_Stamp",           :datetime
    t.column "LanguageCode",         :string,   :limit => 2,  :default => "", :null => false
    t.column "VarName_ID",           :integer,  :limit => 19
    t.column "InstrumentSession_ID", :integer,  :limit => 19
    t.column "InstrumentContent_ID", :integer,  :limit => 19
  end

  add_index "item_usage", ["itemusage_id"], :name => "primary", :unique => true
  add_index "item_usage", ["instrumentsession_id"], :name => "fk_item_usage_instrumentsession_id"
  add_index "item_usage", ["instrumentcontent_id"], :name => "fk_item_usage_instrumentcontent_id"
  add_index "item_usage", ["varname_id"], :name => "fk_item_usage_varname_id"

  create_table "language_list", :id => false, :force => true do |t|
    t.column "LanguageList_ID", :integer,                 :null => false
    t.column "LanguageList",    :text,    :default => "", :null => false
  end

  add_index "language_list", ["languagelist_id"], :name => "primary", :unique => true

  create_table "loinc_instrument_request", :id => false, :force => true do |t|
    t.column "LOINC_InstrumentRequest_ID", :integer, :limit => 19, :null => false
    t.column "LOINCsystem",                :string
    t.column "LOINCscale",                 :string
    t.column "LOINCproperty",              :string
    t.column "LOINCmethod",                :string
    t.column "LOINC_NUM",                  :string
    t.column "LOINCtimeAspect",            :string
    t.column "InstrumentVersion_ID",       :integer, :limit => 19
  end

  add_index "loinc_instrument_request", ["loinc_instrumentrequest_id"], :name => "primary", :unique => true
  add_index "loinc_instrument_request", ["instrumentversion_id"], :name => "fk_loinc_instrument_request_instrumentversion_id"

  create_table "loinc_item_request", :id => false, :force => true do |t|
    t.column "LOINC_ItemRequest_ID", :integer, :limit => 19, :null => false
    t.column "LOINCsystem",          :string
    t.column "LOINCscale",           :string
    t.column "LOINCproperty",        :string
    t.column "LOINCmethod",          :string
    t.column "LOINC_NUM",            :string
    t.column "LOINCtimeAspect",      :string
    t.column "Item_ID",              :integer, :limit => 19
  end

  add_index "loinc_item_request", ["loinc_itemrequest_id"], :name => "primary", :unique => true
  add_index "loinc_item_request", ["item_id"], :name => "fk_loinc_item_request_item_id"

  create_table "null_flavor", :id => false, :force => true do |t|
    t.column "NullFlavor_ID", :integer,                 :null => false
    t.column "NullFlavor",    :string,  :default => "", :null => false
    t.column "DisplayName",   :string,  :default => "", :null => false
    t.column "Description",   :text
  end

  add_index "null_flavor", ["nullflavor_id"], :name => "primary", :unique => true

  create_table "page_usage", :id => false, :force => true do |t|
    t.column "PageUsage_ID",         :integer,  :limit => 19,                 :null => false
    t.column "totalDuration",        :integer
    t.column "pageDuration",         :integer
    t.column "LanguageCode",         :string,   :limit => 2,  :default => "", :null => false
    t.column "serverDuration",       :integer
    t.column "FromGroupNum",         :integer,                                :null => false
    t.column "loadDuration",         :integer
    t.column "DisplayNum",           :integer,                                :null => false
    t.column "networkDuration",      :integer
    t.column "PageUsageSequence",    :integer,                                :null => false
    t.column "pageVacillation",      :integer
    t.column "ToGroupNum",           :integer,                                :null => false
    t.column "Time_Stamp",           :datetime,                               :null => false
    t.column "StatusMsg",            :string
    t.column "InstrumentSession_ID", :integer,  :limit => 19
    t.column "ActionType_ID",        :integer
  end

  add_index "page_usage", ["pageusage_id"], :name => "primary", :unique => true
  add_index "page_usage", ["actiontype_id"], :name => "fk_page_usage_actiontype_id"
  add_index "page_usage", ["instrumentsession_id"], :name => "fk_page_usage_instrumentsession_id"

  create_table "page_usage_event", :id => false, :force => true do |t|
    t.column "PageUsageEvent_ID",      :integer,  :limit => 19,                 :null => false
    t.column "Time_Stamp",             :datetime
    t.column "duration",               :integer,                                :null => false
    t.column "PageUsageEventSequence", :integer,                                :null => false
    t.column "value1",                 :string,                 :default => "", :null => false
    t.column "eventType",              :string,                 :default => "", :null => false
    t.column "value2",                 :string,                 :default => "", :null => false
    t.column "GuiActionType",          :string,                 :default => "", :null => false
    t.column "VarName_ID",             :integer,  :limit => 19
    t.column "PageUsage_ID",           :integer,  :limit => 19
  end

  add_index "page_usage_event", ["pageusageevent_id"], :name => "primary", :unique => true
  add_index "page_usage_event", ["pageusage_id"], :name => "fk_page_usage_event_pageusage_id"
  add_index "page_usage_event", ["varname_id"], :name => "fk_page_usage_event_varname_id"

  create_table "question", :id => false, :force => true do |t|
    t.column "Question_ID", :integer, :limit => 19, :null => false
  end

  add_index "question", ["question_id"], :name => "primary", :unique => true

  create_table "question_localized", :id => false, :force => true do |t|
    t.column "QuestionLocalized_ID", :integer, :limit => 19,                 :null => false
    t.column "LanguageCode",         :string,  :limit => 2,  :default => "", :null => false
    t.column "QuestionString",       :text
    t.column "Question_ID",          :integer, :limit => 19
  end

  add_index "question_localized", ["questionlocalized_id"], :name => "primary", :unique => true
  add_index "question_localized", ["question_id"], :name => "fk_question_localized_question_id"

  create_table "readback", :id => false, :force => true do |t|
    t.column "Readback_ID", :integer, :limit => 19, :null => false
  end

  add_index "readback", ["readback_id"], :name => "primary", :unique => true

  create_table "readback_localized", :id => false, :force => true do |t|
    t.column "ReadbackLocalized_ID", :integer, :limit => 19,                 :null => false
    t.column "LanguageCode",         :string,  :limit => 2,  :default => "", :null => false
    t.column "ReadbackString",       :text
    t.column "Readback_ID",          :integer, :limit => 19
  end

  add_index "readback_localized", ["readbacklocalized_id"], :name => "primary", :unique => true
  add_index "readback_localized", ["readback_id"], :name => "fk_readback_localized_readback_id"

  create_table "reserved_word", :id => false, :force => true do |t|
    t.column "ReservedWord_ID", :integer,                 :null => false
    t.column "ReservedWord",    :string,  :default => "", :null => false
    t.column "Meaning",         :text
  end

  add_index "reserved_word", ["reservedword_id"], :name => "primary", :unique => true

  create_table "semantic_mapping_a", :id => false, :force => true do |t|
    t.column "SemanticMapping_A_ID", :integer, :limit => 19, :null => false
    t.column "CodeDisplayName",      :text
    t.column "Code",                 :text
    t.column "CodeSystem_ID",        :integer
    t.column "Answer_ID",            :integer, :limit => 19
  end

  add_index "semantic_mapping_a", ["semanticmapping_a_id"], :name => "primary", :unique => true
  add_index "semantic_mapping_a", ["answer_id"], :name => "fk_semantic_mapping_a_answer_id"
  add_index "semantic_mapping_a", ["codesystem_id"], :name => "fk_semantic_mapping_a_codesystem_id"

  create_table "semantic_mapping_i_q_a", :id => false, :force => true do |t|
    t.column "SemanticMapping_IQA_ID", :integer, :limit => 19, :null => false
    t.column "Code",                   :text
    t.column "CodeDisplayName",        :text
    t.column "CodeSystem_ID",          :integer
    t.column "InstrumentVersion_ID",   :integer, :limit => 19
    t.column "Question_ID",            :integer, :limit => 19
    t.column "Answer_ID",              :integer, :limit => 19
  end

  add_index "semantic_mapping_i_q_a", ["semanticmapping_iqa_id"], :name => "primary", :unique => true
  add_index "semantic_mapping_i_q_a", ["codesystem_id"], :name => "fk_semantic_mapping_i_q_a_codesystem_id"
  add_index "semantic_mapping_i_q_a", ["answer_id"], :name => "fk_semantic_mapping_i_q_a_answer_id"
  add_index "semantic_mapping_i_q_a", ["instrumentversion_id"], :name => "fk_semantic_mapping_i_q_a_instrumentversion_id"
  add_index "semantic_mapping_i_q_a", ["question_id"], :name => "fk_semantic_mapping_i_q_a_question_id"

  create_table "semantic_mapping_q", :id => false, :force => true do |t|
    t.column "SemanticMapping_Q_ID", :integer, :limit => 19, :null => false
    t.column "CodeDisplayName",      :text
    t.column "Code",                 :text
    t.column "CodeSystem_ID",        :integer
    t.column "Question_ID",          :integer, :limit => 19
  end

  add_index "semantic_mapping_q", ["semanticmapping_q_id"], :name => "primary", :unique => true
  add_index "semantic_mapping_q", ["codesystem_id"], :name => "fk_semantic_mapping_q_codesystem_id"
  add_index "semantic_mapping_q", ["question_id"], :name => "fk_semantic_mapping_q_question_id"

  create_table "semantic_mapping_q_a", :id => false, :force => true do |t|
    t.column "SemanticMapping_QA_ID", :integer, :limit => 19, :null => false
    t.column "CodeDisplayName",       :text
    t.column "Code",                  :text
    t.column "CodeSystem_ID",         :integer
    t.column "Question_ID",           :integer, :limit => 19
    t.column "Answer_ID",             :integer, :limit => 19
  end

  add_index "semantic_mapping_q_a", ["semanticmapping_qa_id"], :name => "primary", :unique => true
  add_index "semantic_mapping_q_a", ["question_id"], :name => "fk_semantic_mapping_q_a_question_id"
  add_index "semantic_mapping_q_a", ["answer_id"], :name => "fk_semantic_mapping_q_a_answer_id"
  add_index "semantic_mapping_q_a", ["codesystem_id"], :name => "fk_semantic_mapping_q_a_codesystem_id"

  create_table "sequence", :id => false, :force => true do |t|
    t.column "SEQ_NAME",  :string,  :limit => 50,                                :default => "", :null => false
    t.column "SEQ_COUNT", :integer, :limit => 38, :precision => 38, :scale => 0
  end

  add_index "sequence", ["seq_name"], :name => "primary", :unique => true

  create_table "sequence_generator_table", :id => false, :force => true do |t|
    t.column "SEQUENCE_NAME",  :string,  :limit => 50,                                :default => "", :null => false
    t.column "SEQUENCE_VALUE", :integer, :limit => 38, :precision => 38, :scale => 0
  end

  add_index "sequence_generator_table", ["sequence_name"], :name => "primary", :unique => true

  create_table "v1_data_element", :id => false, :force => true do |t|
    t.column "V1DataElement_ID",       :integer,  :limit => 19,                  :null => false
    t.column "Time_Stamp",             :datetime
    t.column "WhenAsMS",               :integer,  :limit => 19,                  :null => false
    t.column "DataElementSequence",    :integer,                                 :null => false
    t.column "itemVisits",             :integer
    t.column "DisplayNum",             :integer,                                 :null => false
    t.column "totalDuration",          :integer
    t.column "QuestionAsAsked",        :text
    t.column "pageDuration",           :integer
    t.column "AnswerString",           :text
    t.column "serverDuration",         :integer
    t.column "GroupNum",               :integer
    t.column "loadDuration",           :integer
    t.column "AnswerCode",             :text
    t.column "networkDuration",        :integer
    t.column "LanguageCode",           :string,   :limit => 2
    t.column "Comments",               :text
    t.column "VarName",                :string,   :limit => 200, :default => "", :null => false
    t.column "V1InstrumentSession_ID", :integer,  :limit => 19
  end

  add_index "v1_data_element", ["v1dataelement_id"], :name => "primary", :unique => true
  add_index "v1_data_element", ["v1instrumentsession_id"], :name => "fk_v1_data_element_v1instrumentsession_id"

  create_table "v1_instrument_session", :id => false, :force => true do |t|
    t.column "V1InstrumentSession_ID",    :integer,  :limit => 19,                 :null => false
    t.column "StatusMsg",                 :string
    t.column "MaxGroup",                  :integer
    t.column "InstrumentVersionName",     :string,                 :default => "", :null => false
    t.column "MaxVarNum",                 :integer
    t.column "LastAccessTime",            :datetime,                               :null => false
    t.column "InstrumentVersionFileName", :text
    t.column "CurrentGroup",              :integer
    t.column "InstrumentSessionFileName", :text
    t.column "LanguageCode",              :string,   :limit => 2
    t.column "NumVars",                   :integer
    t.column "VarListMD5",                :string
    t.column "InstrumentStartingGroup",   :integer
    t.column "NumGroups",                 :integer
    t.column "ActionType",                :string
    t.column "Finished",                  :integer
    t.column "DisplayNum",                :integer
    t.column "StartTime",                 :datetime,                               :null => false
  end

  add_index "v1_instrument_session", ["v1instrumentsession_id"], :name => "primary", :unique => true

  create_table "v1_item_usage", :id => false, :force => true do |t|
    t.column "V1ItemUsage_ID",         :integer,  :limit => 19,                  :null => false
    t.column "AnswerString",           :text
    t.column "Time_Stamp",             :datetime
    t.column "ItemUsageSequence",      :integer,                                 :null => false
    t.column "WhenAsMS",               :integer,  :limit => 19
    t.column "DataElementSequence",    :integer,                                 :null => false
    t.column "itemVisits",             :integer
    t.column "DisplayNum",             :integer,                                 :null => false
    t.column "totalDuration",          :integer
    t.column "QuestionAsAsked",        :text
    t.column "pageDuration",           :integer
    t.column "serverDuration",         :integer
    t.column "GroupNum",               :integer
    t.column "loadDuration",           :integer
    t.column "AnswerCode",             :text
    t.column "networkDuration",        :integer
    t.column "LanguageCode",           :string,   :limit => 2
    t.column "Comments",               :text
    t.column "VarName",                :string,   :limit => 200, :default => "", :null => false
    t.column "V1InstrumentSession_ID", :integer,  :limit => 19
  end

  add_index "v1_item_usage", ["v1itemusage_id"], :name => "primary", :unique => true
  add_index "v1_item_usage", ["v1instrumentsession_id"], :name => "fk_v1_item_usage_v1instrumentsession_id"

  create_table "v1_sequence_generator_table", :id => false, :force => true do |t|
    t.column "SEQUENCE_NAME",  :string,  :limit => 50,                                :default => "", :null => false
    t.column "SEQUENCE_VALUE", :integer, :limit => 38, :precision => 38, :scale => 0
  end

  add_index "v1_sequence_generator_table", ["sequence_name"], :name => "primary", :unique => true

  create_table "validation", :id => false, :force => true do |t|
    t.column "Validation_ID", :integer, :limit => 19, :null => false
    t.column "MaxVal",        :string
    t.column "OtherVals",     :string
    t.column "MinVal",        :string
    t.column "InputMask",     :string
  end

  add_index "validation", ["validation_id"], :name => "primary", :unique => true

  create_table "var_name", :id => false, :force => true do |t|
    t.column "VarName_ID", :integer, :limit => 19,                 :null => false
    t.column "VarName",    :string,                :default => "", :null => false
  end

  add_index "var_name", ["varname_id"], :name => "primary", :unique => true

end
